services:
  lostlink-server:
    build: .
    container_name: lostlink-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://lostlink-database:5432/lostlink
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - lostlink-database

  lostlink-database:
    image: postgres:16
    container_name: lostlink-database
    environment:
      POSTGRES_DB: lostlink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
