version: '3.8'

services:
  db:
    image: postgres:16
    container_name: lostlink-db
    restart: always
    environment:
      POSTGRES_DB: lostlink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - lostlink_pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: lostlink-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lostlink
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRINGDOC_SWAGGER_UI_PATH: /v1/docs

volumes:
  lostlink_pg_data:
